// <auto-generated />
using System;
using Lumen.Modules.Youtube.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lumen.Modules.Youtube.Data.Migrations
{
    [DbContext(typeof(YoutubeContext))]
    [Migration("20250214144308_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("youtubewatchlist")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lumen.Modules.Youtube.Common.Models.YoutubeWatchlistPointInTime", b =>
                {
                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AmountVideos")
                        .HasColumnType("integer");

                    b.Property<int>("SecondsDuration")
                        .HasColumnType("integer");

                    b.HasKey("Time");

                    b.ToTable("YoutubeWatchlist", "youtubewatchlist");
                });
#pragma warning restore 612, 618
        }
    }
}
